name = "HyperFlows"
uuid = "fd652113-1c94-4d30-a59b-41e6f6419c37"
authors = ["Nathan Davey", "Imperial College London"]
version = "0.1.0"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
